### ISSUE TITLE
Javascript exception on first launch

### ISSUE THREAD

**Issue by iandesj** [akroma-project/akroma-wallet-desktop#2]
On first launch there is a javascript exception being thrown. I suspect this is being thrown when we upgraded the binary to executable. Putting here for investigation later.

**Comment by detroitpro** [comment]
Is this the error: 
![image](https://user-images.githubusercontent.com/49996/39850896-ce7576bc-53e1-11e8-8b21-7c503422f553.png)

**Comment by detroitpro** [comment]
![image](https://user-images.githubusercontent.com/49996/39850905-dd60c406-53e1-11e8-8738-6bd39ee75930.png)

**Comment by StephenKoller** [comment]
Found a potential fix for local development, but unsure if this could help affect installed executables.

https://ethereum.stackexchange.com/questions/23719/invalid-json-rpc-response-undefined-when-running-web3-eth-accounts-node

"To solve it, the trick is to run testrpc in another terminal window"
