### ISSUE TITLE
Akroma wallet 0.0.5 - zero balance and no Txs after accumulation of almost 4500 coins

### ISSUE THREAD

**Issue by Shekelme** [akroma-project/akroma-wallet-desktop#60]
I was storing almost 4500 AKA on my Windows PC (wallet 0.0.5 installed from scratch). I was mining for masternode. In the "Settings" I chose non-default path for storing Akroma data. Once after wallet restart it began to download all data again, and then I found that Akroma wallet is storing it's data under some default path (C:\Users\rabinovitch\.akroma). In previously used folder (K:\Akroma.data) I can't find any wallet-related file, so as in newly created by Akroma folder.

How can I get back access to my funds?

**Comment by Shekelme** [comment]
looks like the Akroma wallet moved an UTC file to new location but for some reason was not able to work with it. Now I found this file and placed it back to my custom folder. My AKA coins are OK now. But please make the wallet better and smarter.

**Comment by astronautskaspars** [comment]
You should always backup your UTC/JSON files, in a safe location.

The wallet will get smarter over time, but you still need to make sure you have your files in a secure place! Just in case your computer is not accessible one day, or the backup folder gets deleted by accident.
