### ISSUE TITLE
Akroma Setup 005 

### ISSUE THREAD

**Issue by Dukulele1** [akroma-project/akroma-wallet-desktop#61]
I am stuck at the attached screen when I run Akroma.Setup.0.0.5.exe Any help would be much appreciated.

Thanks

![walletssissue](https://user-images.githubusercontent.com/42484731/44295148-b7862600-a2e6-11e8-8625-25d62bd43bd0.PNG)

**Comment by detroitpro** [comment]
New build coming soon that will use remote transaction source by default.
