### ISSUE TITLE
Import with running instance

### ISSUE THREAD

**Issue by detroitpro** [akroma-project/akroma-wallet-desktop#74]
I'm not sure if this is a bug or feature request or already on a todo list somewhere. 

When I use a running geth instance, I am seeing different wallets and wondering how to best handle/import/etc them. What does wallet import do in this case?

![image](https://user-images.githubusercontent.com/49996/45375795-0496a880-b5c4-11e8-9f21-9d00958ded96.png)

+ @astronautskaspars

**Comment by astronautskaspars** [comment]
looks like a bug. 
Nothing like that on my machine, I'm going to try this out on Win10 

How his you set this up?
